experiment:
  dataset: movielens_1m
  data_config:
    strategy: dataset
    dataset_path: data/movielens_1m/dataset.tsv
  splitting:
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
  models:
    ItemKNN:
      meta:
        hyper_opt_alg: grid
        save_recs: True
      neighbors: [50, 100]
      similarity: cosine
  evaluation:
    simple_metrics: [nDCG, ACLT, ARP, Precision,ItemCoverage,EPC,Gini]
  top_k: 10