experiment:
  gpu: 1
  path_output_rec_performance: C:/Users/ReadyToUse/PycharmProjects/pythonProject/results/test_results/rec_performance

  dataset: artgraph
  data_config:
    strategy: fixed
    train_path: C:/Users/ReadyToUse/PycharmProjects/pythonProject/results/artgraph/valutation_file/FunkSVD/train.tsv
    test_path: C:/Users/ReadyToUse/PycharmProjects/pythonProject/results/artgraph/splitting/test_set_positive/test.tsv

  evaluation:
    simple_metrics: [MAP, Precision, MAR, Recall, F1, nDCG, Gini, ItemCoverage, EFD, EPC]
    paired_ttest: True
    wilcoxon_test: False

  models:
    ProxyRecommender:
      path: C:/Users/ReadyToUse/PycharmProjects/pythonProject/results/artgraph/recs/FunkSVD_seed=42_e=2_bs=49337_factors=10_lr=0$001_reg_w=0$1_reg_b=0$001_it=2.tsv

  top_k: 5